---
# tasks file for tmux
- name: "Including tmux installation"
  ansible.builtin.include_tasks: install.yml

- name: "Including tmux configuration setup"
  ansible.builtin.include_tasks: setup.yml

- name: "Including clean-up"
  ansible.builtin.include_tasks: cleanup.yml
  when: tmux_remove_backup|bool
