---
- name: "Configuring Tmux Template for {{ item.name }}"
  ansible.builtin.template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    backup: true
  when: item.enable|bool
  loop: "{{ tmux_templates }}"
